apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-api-deploy
  labels:
   app: card-api-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: card-api-pod
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1    
  template:
    metadata:
      labels:
        app: card-api-pod
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: card-api-pod
        image: guydbentley/cardops-cardsapi:1.0
        imagePullPolicy: Always
        resources:
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2883
