apiVersion: v1
kind: Service
metadata:
  name: cardapi-nodeport
spec:
  type: NodePort
  ports:
  - port:  2883
    targetPort: 2883
    nodePort: 30868
    protocol: TCP
  selector:
    app: card-api-pod